# Generated by Django 6.1.1 on 2026-09-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ALUMNO',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_division', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DIVISION',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'DOCENTE',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GRADO',
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id_padre', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PADRE',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_turno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TURNO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='AdaptacionAlumno',
            fields=[
                ('id_adaptacion', models.AutoField(primary_key=True, serialize=False)),
                ('adaptaciones_necesarias', models.TextField(blank=True, null=True)),
                ('estrategias_funcionales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='adaptaciones', to='core.alumno')),
            ],
            options={
                'db_table': 'ADAPTACION_ALUMNO',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='division',
            field=models.ForeignKey(db_column='id_division', on_delete=django.db.models.deletion.PROTECT, to='core.division'),
        ),
        migrations.AddField(
            model_name='division',
            name='grado',
            field=models.ForeignKey(db_column='id_grado', on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='core.grado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.ForeignKey(db_column='id_grado', on_delete=django.db.models.deletion.PROTECT, to='core.grado'),
        ),
        migrations.CreateModel(
            name='InformacionMedica',
            fields=[
                ('id_informacion_medica', models.AutoField(primary_key=True, serialize=False)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('celiaquia', models.BooleanField(blank=True, null=True)),
                ('diabetes', models.BooleanField(blank=True, null=True)),
                ('medicacion_necesaria', models.TextField(blank=True, null=True)),
                ('medicacion_emergencia', models.TextField(blank=True, null=True)),
                ('informacion_medica_emergencia', models.TextField(blank=True, null=True)),
                ('restricciones_educacion_fisica', models.TextField(blank=True, null=True)),
                ('alumno', models.OneToOneField(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='informacion_medica', to='core.alumno')),
            ],
            options={
                'db_table': 'INFORMACION_MEDICA',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='core.alumno')),
                ('padre', models.ForeignKey(db_column='id_padre', on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='core.padre')),
            ],
            options={
                'db_table': 'INFORME',
            },
        ),
        migrations.CreateModel(
            name='PersonaRetiro',
            fields=[
                ('id_persona_retiro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('vinculo', models.CharField(blank=True, max_length=100, null=True)),
                ('autorizado', models.BooleanField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='personas_retiro', to='core.alumno')),
            ],
            options={
                'db_table': 'PERSONA_RETIRO',
            },
        ),
        migrations.CreateModel(
            name='SituacionAsistencia',
            fields=[
                ('id_situacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='situaciones', to='core.alumno')),
            ],
            options={
                'db_table': 'SITUACION_ASISTENCIA',
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.ForeignKey(db_column='id_division', on_delete=django.db.models.deletion.CASCADE, to='core.division')),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.docente')),
                ('grado', models.ForeignKey(db_column='id_grado', on_delete=django.db.models.deletion.CASCADE, to='core.grado')),
                ('turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
            options={
                'db_table': 'ASIGNACION_DOCENTE',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.PROTECT, to='core.turno'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id_supervisor', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'SUPERVISOR',
            },
        ),
        migrations.AddField(
            model_name='padre',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id_directivo', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'DIRECTIVO',
            },
        ),
        migrations.CreateModel(
            name='PadreAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.alumno')),
                ('padre', models.ForeignKey(db_column='id_padre', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.padre')),
            ],
            options={
                'db_table': 'PADRE_ALUMNO',
                'unique_together': {('padre', 'alumno')},
            },
        ),
    ]
